### ISSUE TITLE
运行环境是什么？

### ISSUE THREAD

**Issue by ghost** [cq1228/junit5TestCodeHelper#1]
问一下，运行环境和导包内容是什么啊，导入本地没有导包相关信息，这个项目是maven管理的还是其他工具管理的？

**Comment by cq1228** [comment]
gradle 环境，类似maven

**Comment by cq1228** [comment]
已上传工程文件之version分支

**Comment by cq1228** [comment]
Gradel，类似mvn



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月12日(周二) 中午11:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cq1228/junit5TestCodeHelper] 运行环境是什么？ (Issue #1)




 
问一下，运行环境和导包内容是什么啊，导入本地没有导包相关信息，这个项目是maven管理的还是其他工具管理的？
